.TH CSMAKE 1 "10 June 2019"
.\"
.\" (C) Copyright 2019 Diomidis Spinellis
.\"
.\" This file is part of CScout.
.\"
.\" CScout is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" CScout is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with CScout.  If not, see <http://www.gnu.org/licenses/>.
.\"
.SH NAME
csmake \- CScout make
.SH SYNOPSIS
\fBcsmake\fP
[\fImake(1) options\fP]
.SH DESCRIPTION
\fIcsmake\fP is a wrapper around \fImake\fP and typical C compilation
commands.
When invoked instead of \fImake\fP on a clean (unbuilt) system,
it will build the system in the same way as \fImake\fP.
As a side-effect it will monitor the invocations of
\fIcc(1)\fP,
\fIgcc(1)\fP,
\fIclang(1)\fP,
\fIar(1)\fP,
\fIld(1)\fP, and
\fImv(1)\fP commands and record their environment and arguments.
With those data it will generate a \fICScout\fP project specification
that can be used to process the project that was compiled.
The project specification is saved into a file named \fImake.cs\fP.
Moreover, a separate CScout .cs file is generated for each excecutable
in cscout_projects directory.
.PP
To allow \fIcsmake\fP to be used as a drop in replacement in
build sequences that execute multiple \fImake\fP commands,
you can create a \fC/tmp/csmake-spy\fP, which will be used
to create rules for the superset of all \fImake\fP-generated executables.
.SH EXAMPLE
The following commands are often the only ones required to process
a typical C project.
.PP
.DS
.ft C
.nf
make clean
csmake
cscout make.cs
.ft P
.fi
.DE
.PP
If you want to use \fIcsmake\fP with another C compiler, prepend
\fBCC=\fIcompiler-name\fR to the \fIcsmake\fP invocation,
as shown in the following example.
.PP
.DS
.ft C
.nf
CC=x86_64-w64-gcc csmake
.ft P
.fi
.DE
.PP
.SH "SEE ALSO"
cscout(1)
.SH AUTHOR
(C) Copyright 2006-2016 Diomidis Spinellis.
