-- Extend the ids table with its attributes
-- Various RDBU tests only provide eid and name to keep things simple

ALTER TABLE ids ADD COLUMN READONLY BOOLEAN;
ALTER TABLE ids ADD COLUMN UNDEFMACRO BOOLEAN;
ALTER TABLE ids ADD COLUMN MACRO BOOLEAN;
ALTER TABLE ids ADD COLUMN MACROARG BOOLEAN;
ALTER TABLE ids ADD COLUMN ORDINARY BOOLEAN;
ALTER TABLE ids ADD COLUMN SUETAG BOOLEAN;
ALTER TABLE ids ADD COLUMN SUMEMBER BOOLEAN;
ALTER TABLE ids ADD COLUMN LABEL BOOLEAN;
ALTER TABLE ids ADD COLUMN TYPEDEF BOOLEAN;
ALTER TABLE ids ADD COLUMN ENUM BOOLEAN;
ALTER TABLE ids ADD COLUMN YACC BOOLEAN;
ALTER TABLE ids ADD COLUMN FUN BOOLEAN;
ALTER TABLE ids ADD COLUMN CSCOPE BOOLEAN;
ALTER TABLE ids ADD COLUMN LSCOPE BOOLEAN;
ALTER TABLE ids ADD COLUMN UNUSED BOOLEAN;

ALTER TABLE adb.ids ADD COLUMN READONLY BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN UNDEFMACRO BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN MACRO BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN MACROARG BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN ORDINARY BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN SUETAG BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN SUMEMBER BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN LABEL BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN TYPEDEF BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN ENUM BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN YACC BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN FUN BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN CSCOPE BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN LSCOPE BOOLEAN;
ALTER TABLE adb.ids ADD COLUMN UNUSED BOOLEAN;

UPDATE ids SET
  readonly=1,
  undefmacro=1,
  macro=1,
  macroarg=1,
  ordinary=1,
  suetag=1,
  sumember=1,
  label=1,
  typedef=1,
  enum=1,
  yacc=1,
  fun=1,
  cscope=1,
  lscope=1,
  unused=1;

UPDATE adb.ids SET
  readonly=0,
  undefmacro=0,
  macro=0,
  macroarg=0,
  ordinary=0,
  suetag=0,
  sumember=0,
  label=0,
  typedef=0,
  enum=0,
  yacc=0,
  fun=0,
  cscope=0,
  lscope=0,
  unused=0;
