-- Add to functionmetrics missing file records, and update any existing ones
-- with the maximum of the existing and the new ones.

INSERT OR REPLACE INTO functionmetrics
  SELECT
    fgm.global_id AS functionid,
    Coalesce(fma.precpp, fmb.precpp) AS precpp,
    Max(Coalesce(fma.nchar, fmb.nchar), Coalesce(fmb.nchar, fma.nchar)) AS nchar,
    Max(Coalesce(fma.nccomment, fmb.nccomment), Coalesce(fmb.nccomment, fma.nccomment)) AS nccomment,
    Max(Coalesce(fma.nspace, fmb.nspace), Coalesce(fmb.nspace, fma.nspace)) AS nspace,
    Max(Coalesce(fma.nlcomment, fmb.nlcomment), Coalesce(fmb.nlcomment, fma.nlcomment)) AS nlcomment,
    Max(Coalesce(fma.nbcomment, fmb.nbcomment), Coalesce(fmb.nbcomment, fma.nbcomment)) AS nbcomment,
    Max(Coalesce(fma.nline, fmb.nline), Coalesce(fmb.nline, fma.nline)) AS nline,
    Max(Coalesce(fma.maxlinelen, fmb.maxlinelen), Coalesce(fmb.maxlinelen, fma.maxlinelen)) AS maxlinelen,
    Max(Coalesce(fma.maxstmtlen, fmb.maxstmtlen), Coalesce(fmb.maxstmtlen, fma.maxstmtlen)) AS maxstmtlen,
    Max(Coalesce(fma.maxstmtnest, fmb.maxstmtnest), Coalesce(fmb.maxstmtnest, fma.maxstmtnest)) AS maxstmtnest,
    Max(Coalesce(fma.maxbracenest, fmb.maxbracenest), Coalesce(fmb.maxbracenest, fma.maxbracenest)) AS maxbracenest,
    Max(Coalesce(fma.maxbracknest, fmb.maxbracknest), Coalesce(fmb.maxbracknest, fma.maxbracknest)) AS maxbracknest,
    Max(Coalesce(fma.bracenest, fmb.bracenest), Coalesce(fmb.bracenest, fma.bracenest)) AS bracenest,
    Max(Coalesce(fma.bracknest, fmb.bracknest), Coalesce(fmb.bracknest, fma.bracknest)) AS bracknest,
    Max(Coalesce(fma.nuline, fmb.nuline), Coalesce(fmb.nuline, fma.nuline)) AS nuline,
    Max(Coalesce(fma.nppdirective, fmb.nppdirective), Coalesce(fmb.nppdirective, fma.nppdirective)) AS nppdirective,
    Max(Coalesce(fma.nppcond, fmb.nppcond), Coalesce(fmb.nppcond, fma.nppcond)) AS nppcond,
    Max(Coalesce(fma.nppfmacro, fmb.nppfmacro), Coalesce(fmb.nppfmacro, fma.nppfmacro)) AS nppfmacro,
    Max(Coalesce(fma.nppomacro, fmb.nppomacro), Coalesce(fmb.nppomacro, fma.nppomacro)) AS nppomacro,
    Max(Coalesce(fma.ntoken, fmb.ntoken), Coalesce(fmb.ntoken, fma.ntoken)) AS ntoken,
    Max(Coalesce(fma.nstmt, fmb.nstmt), Coalesce(fmb.nstmt, fma.nstmt)) AS nstmt,
    Max(Coalesce(fma.nop, fmb.nop), Coalesce(fmb.nop, fma.nop)) AS nop,
    Max(Coalesce(fma.nuop, fmb.nuop), Coalesce(fmb.nuop, fma.nuop)) AS nuop,
    Max(Coalesce(fma.nnconst, fmb.nnconst), Coalesce(fmb.nnconst, fma.nnconst)) AS nnconst,
    Max(Coalesce(fma.nclit, fmb.nclit), Coalesce(fmb.nclit, fma.nclit)) AS nclit,
    Max(Coalesce(fma.nstring, fmb.nstring), Coalesce(fmb.nstring, fma.nstring)) AS nstring,
    Max(Coalesce(fma.nppconcatop, fmb.nppconcatop), Coalesce(fmb.nppconcatop, fma.nppconcatop)) AS nppconcatop,
    Max(Coalesce(fma.nppstringop, fmb.nppstringop), Coalesce(fmb.nppstringop, fma.nppstringop)) AS nppstringop,
    Max(Coalesce(fma.nif, fmb.nif), Coalesce(fmb.nif, fma.nif)) AS nif,
    Max(Coalesce(fma.nelse, fmb.nelse), Coalesce(fmb.nelse, fma.nelse)) AS nelse,
    Max(Coalesce(fma.nswitch, fmb.nswitch), Coalesce(fmb.nswitch, fma.nswitch)) AS nswitch,
    Max(Coalesce(fma.ncase, fmb.ncase), Coalesce(fmb.ncase, fma.ncase)) AS ncase,
    Max(Coalesce(fma.ndefault, fmb.ndefault), Coalesce(fmb.ndefault, fma.ndefault)) AS ndefault,
    Max(Coalesce(fma.nbreak, fmb.nbreak), Coalesce(fmb.nbreak, fma.nbreak)) AS nbreak,
    Max(Coalesce(fma.nfor, fmb.nfor), Coalesce(fmb.nfor, fma.nfor)) AS nfor,
    Max(Coalesce(fma.nwhile, fmb.nwhile), Coalesce(fmb.nwhile, fma.nwhile)) AS nwhile,
    Max(Coalesce(fma.ndo, fmb.ndo), Coalesce(fmb.ndo, fma.ndo)) AS ndo,
    Max(Coalesce(fma.ncontinue, fmb.ncontinue), Coalesce(fmb.ncontinue, fma.ncontinue)) AS ncontinue,
    Max(Coalesce(fma.ngoto, fmb.ngoto), Coalesce(fmb.ngoto, fma.ngoto)) AS ngoto,
    Max(Coalesce(fma.nreturn, fmb.nreturn), Coalesce(fmb.nreturn, fma.nreturn)) AS nreturn,
    Max(Coalesce(fma.npid, fmb.npid), Coalesce(fmb.npid, fma.npid)) AS npid,
    Max(Coalesce(fma.nfid, fmb.nfid), Coalesce(fmb.nfid, fma.nfid)) AS nfid,
    Max(Coalesce(fma.nmid, fmb.nmid), Coalesce(fmb.nmid, fma.nmid)) AS nmid,
    Max(Coalesce(fma.nid, fmb.nid), Coalesce(fmb.nid, fma.nid)) AS nid,
    Max(Coalesce(fma.nupid, fmb.nupid), Coalesce(fmb.nupid, fma.nupid)) AS nupid,
    Max(Coalesce(fma.nufid, fmb.nufid), Coalesce(fmb.nufid, fma.nufid)) AS nufid,
    Max(Coalesce(fma.numid, fmb.numid), Coalesce(fmb.numid, fma.numid)) AS numid,
    Max(Coalesce(fma.nuid, fmb.nuid), Coalesce(fmb.nuid, fma.nuid)) AS nuid,
    Max(Coalesce(fma.nlabel, fmb.nlabel), Coalesce(fmb.nlabel, fma.nlabel)) AS nlabel,
    Max(Coalesce(fma.nmacroexpandtoken, fmb.nmacroexpandtoken), Coalesce(fmb.nmacroexpandtoken, fma.nmacroexpandtoken)) AS nmacroexpandtoken,
    Max(Coalesce(fma.ngnsoc, fmb.ngnsoc), Coalesce(fmb.ngnsoc, fma.ngnsoc)) AS ngnsoc,
    Max(Coalesce(fma.nmparam, fmb.nmparam), Coalesce(fmb.nmparam, fma.nmparam)) AS nmparam,
    Max(Coalesce(fma.nfparam, fmb.nfparam), Coalesce(fmb.nfparam, fma.nfparam)) AS nfparam,
    Max(Coalesce(fma.neparam, fmb.neparam), Coalesce(fmb.neparam, fma.neparam)) AS neparam,
    Max(Coalesce(fma.fanin, fmb.fanin), Coalesce(fmb.fanin, fma.fanin)) AS fanin,
    Max(Coalesce(fma.fanout, fmb.fanout), Coalesce(fmb.fanout, fma.fanout)) AS fanout,
    Max(Coalesce(fma.ccycl1, fmb.ccycl1), Coalesce(fmb.ccycl1, fma.ccycl1)) AS ccycl1,
    Max(Coalesce(fma.ccycl2, fmb.ccycl2), Coalesce(fmb.ccycl2, fma.ccycl2)) AS ccycl2,
    Max(Coalesce(fma.ccycl3, fmb.ccycl3), Coalesce(fmb.ccycl3, fma.ccycl3)) AS ccycl3,
    Max(Coalesce(fma.cstruc, fmb.cstruc), Coalesce(fmb.cstruc, fma.cstruc)) AS cstruc,
    Max(Coalesce(fma.chal, fmb.chal), Coalesce(fmb.chal, fma.chal)) AS chal,
    Max(Coalesce(fma.iflow, fmb.iflow), Coalesce(fmb.iflow, fma.iflow)) AS iflow
  FROM
    adb.functionmetrics AS fma
    LEFT JOIN functionid_to_global_map AS fgm ON fgm.id = fma.functionid
    LEFT JOIN functionmetrics AS fmb ON fmb.functionid = fgm.global_id
      AND fmb.precpp = fma.precpp;
