#!/usr/bin/env python3
#
# (C) Copyright 2008-2026 Diomidis Spinellis
# (C) Copyright 2026 Ujjwal Aggarwal
#
# This file is part of CScout.
#
# CScout is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CScout is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CScout.  If not, see <http://www.gnu.org/licenses/>.
#
#
# cscoco.py -- generate a CScout workspace file from
# a compile_commands.json compilation database.
#

import argparse
import json
import os
import sys


def parse_flags(entry):
    """
    Extract preprocessor defines and include paths from a
    compile_commands.json entry.

    An entry may carry its compiler invocation either as a single
    'command' string or as an 'arguments' list.  The arguments form
    is preferred because it avoids shell-quoting ambiguity; the
    command form is used as a fallback.

    Returns (defines, includes) where each is a list of strings:
      defines  -- bare macro names or NAME=VALUE pairs, without the -D
      includes -- directory paths, without the -I
    """
    # Prefer the pre-split arguments array; fall back to shell split.
    if 'arguments' in entry:
        parts = entry['arguments']
    else:
        parts = entry['command'].split()

    defines = []
    includes = []
    i = 0
    while i < len(parts):
        part = parts[i]
        if part == '-D':
            # -D NAME (space-separated form)
            if i + 1 < len(parts):
                defines.append(parts[i + 1])
                i += 2
            else:
                i += 1
        elif part.startswith('-D'):
            # -DNAME or -DNAME=VALUE (attached form)
            defines.append(part[2:])
            i += 1
        elif part == '-I':
            # -I path (space-separated form)
            if i + 1 < len(parts):
                includes.append(parts[i + 1])
                i += 2
            else:
                i += 1
        elif part.startswith('-I'):
            # -Ipath (attached form)
            includes.append(part[2:])
            i += 1
        else:
            i += 1

    return defines, includes


def generate_cs(compile_commands_path, output_path, project_name):
    """
    Read compile_commands.json and write the corresponding CScout
    workspace file.

    Each C translation unit in the compilation database becomes a
    block in the .cs file that sets up the preprocessor environment
    (defines and include paths) exactly as the original compiler
    invocation did, then processes the source file.
    """
    
    # Find the CScout installation / config directory
    if os.path.isdir('.cscout'):
        instdir = '.cscout'
    elif 'CSCOUT_HOME' in os.environ:
        instdir = os.environ['CSCOUT_HOME']
    elif 'HOME' in os.environ and os.path.isdir(os.path.join(os.environ['HOME'], '.cscout')):
        instdir = os.path.join(os.environ['HOME'], '.cscout')
    elif os.path.isdir('test/csmake/include/cscout'):
        instdir = 'test/csmake/include/cscout'
    else:
        instdir = 'INSTALL_INCLUDE'

    predefs = os.path.join(instdir, 'csmake-pre-defs.h')
    postdefs = os.path.join(instdir, 'csmake-post-defs.h')

    if not os.path.exists(predefs):
        print(
            f'Error: {predefs} not found.\n'
            f'Create {instdir} and copy '
            f'csmake-pre-defs.h into it from the CScout installation.',
            file=sys.stderr)
        sys.exit(1)

    with open(compile_commands_path, encoding='utf-8') as f:
        entries = json.load(f)

    # Skip non-C files; CScout analyses C, not C++.
    c_entries = [e for e in entries if e['file'].endswith('.c')]

    if not c_entries:
        print('Warning: no .c files found in compilation database.',
              file=sys.stderr)

    with open(output_path, 'w', encoding='utf-8') as out:
        out.write(
            f'/*\n'
            f' * Generated by cscoco\n'
            f' * Source: {compile_commands_path}\n'
            f' */\n\n')
        out.write(f'#pragma project "{project_name}"\n')
        out.write(f'#pragma block_enter\n\n')

        for entry in c_entries:
            filepath = entry['file']
            directory = entry['directory']
            defines, includes = parse_flags(entry)

            out.write(
                f'#pragma echo "Processing '
                f'{os.path.basename(filepath)}\\n"\n')
            out.write(f'#pragma block_enter\n')
            out.write(f'#pragma clear_defines\n')
            out.write(f'#pragma clear_include\n')
            out.write(f'#pragma pushd "{directory}"\n')

            # Pre-defs supply CScout's mock standard headers and the
            # built-in compiler macro definitions (e.g. __GNUC__).
            out.write(f'#include "{predefs}"\n')

            for d in defines:
                if '=' in d:
                    name, val = d.split('=', 1)
                    out.write(f'#define {name} {val}\n')
                else:
                    out.write(f'#define {d}\n')

            for inc in includes:
                out.write(f'#pragma includepath "{inc}"\n')

            # Post-defs close any open constructs from pre-defs.
            out.write(f'#include "{postdefs}"\n')
            out.write(f'#pragma process "{filepath}"\n')
            out.write(f'#pragma popd\n')
            out.write(f'#pragma block_exit\n\n')

        out.write(f'#pragma block_exit\n')

    print(f'Generated {output_path} with {len(c_entries)} C file(s).')


def main():
    parser = argparse.ArgumentParser(
        description='Generate a CScout workspace file from a compile_commands.json compilation database.')
    parser.add_argument('compile_commands',
                        help='Path to the compile_commands.json file')
    parser.add_argument('output',
                        help='Path to the output .cs workspace file')
    parser.add_argument('project_name',
                        help='Name of the project (optional; defaults to the name of the directory above the build directory)',
                        nargs='?',
                        default=None)
    args = parser.parse_args()

    project = args.project_name
    if project is None:
        build_dir = os.path.dirname(os.path.abspath(args.compile_commands))
        project = os.path.basename(os.path.dirname(build_dir))

    generate_cs(args.compile_commands, args.output, project)


if __name__ == '__main__':
    main()
