/*
 * (C) Copyright 2001-2026 Diomidis Spinellis
 *
 * This file is part of CScout.
 *
 * CScout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CScout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CScout.  If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * Portable graph display abstraction
 *
 */

#include <map>
#include <string>
#include <deque>
#include <vector>
#include <stack>
#include <iterator>
#include <iostream>
#include <fstream>
#include <list>
#include <set>
#include <utility>
#include <functional>
#include <algorithm>		// set_difference
#include <cctype>
#include <sstream>		// ostringstream
#include <cstdio>		// perror, rename
#include <cstdlib>		// atoi
#include <cerrno>		// errno

#include "swill.h"
#include "getopt.h"

#include <regex.h>

#include "cpp.h"
#include "debug.h"
#include "error.h"
#include "parse.tab.h"
#include "attr.h"
#include "metrics.h"
#include "fileid.h"
#include "tokid.h"
#include "token.h"
#include "ptoken.h"
#include "fchar.h"
#include "pltoken.h"
#include "macro.h"
#include "pdtoken.h"
#include "eclass.h"
#include "ctoken.h"
#include "type.h"
#include "stab.h"
#include "fdep.h"
#include "version.h"
#include "call.h"
#include "fcall.h"
#include "mcall.h"
#include "compiledre.h"
#include "html.h"
#include "option.h"

#include "gdisplay.h"

#if defined(unix) || defined(__unix__) || defined(__MACH__)
#include <sys/types.h>		// mkdir
#include <sys/stat.h>		// mkdir
#include <unistd.h>		// unlink
#elif defined(WIN32)
#include <io.h>			// mkdir
#include <fcntl.h>		// O_BINARY
#endif

void
GDDot::head(const char *fname, const char *, bool empty_node) {
	fprintf(fdot, "#!/usr/local/bin/dot\n"
		"#\n# Generated by CScout %s - %s\n#\n\n"
		"digraph %s {\n",
		Version::get_revision().c_str(),
		Version::get_date().c_str(), fname);
	if (Option::dot_graph_options->get().length() > 0)
		fprintf(fdot, "\t%s;\n", Option::dot_graph_options->get().c_str());
	if (empty_node)			// Empty nodes
		fprintf(fdot, "\tnode [height=.001,width=0.000001,shape=box,label=\"\",fontsize=8];\n");
	else
		fprintf(fdot, "\tnode [%s];\n", Option::dot_node_options->get().c_str());
	fprintf(fdot, "\tedge [%s];\n", Option::dot_edge_options->get().c_str());
}

void
GDDotImage::head(const char *fname, const char *title, bool empty_node)
{
	#if defined(unix) || defined(__unix__) || defined(__MACH__)
	dot_dir = "/tmp";
	#elif defined(WIN32)
	char *tmp = getenv("TEMP");
	dot_dir = tmp ? tmp : ".";
	#else
	#error "Don't know how to obtain temporary directory"
	#endif
	dot_dir += "/CS-XXXXXX";
	vector<char> mutable_dot_dir(dot_dir.begin(), dot_dir.end());
	mutable_dot_dir.push_back('\0');
	if (mkdtemp(mutable_dot_dir.data()) == NULL) {
		html_perror(fo, "Unable to create temporary directory " + dot_dir, true);
		return;
	}
	dot_dir = mutable_dot_dir.data();
	dot = dot_dir + "/in.dot";
	img = dot_dir + "/out.img";
	fdot = fopen(dot.c_str(), "w");
	if (fdot == NULL) {
		html_perror(fo, "Unable to open " + dot + " for writing", true);
		return;
	}
	GDDot::head(fname, title, empty_node);
}

void
GDDotImage::tail()
{
	GDDot::tail();
	fclose(fdot);
	/*
	 * Changing to the tmp directory overcomes the problem of Cygwin
	 * differences between CScout and dot file paths
	 */
	string cmd = "cd " + dot_dir + " && dot -T" + string(format) + " in.dot -oout.img";
	if (DP())
		cout << cmd << '\n';
	if (system(cmd.c_str()) != 0) {
		html_perror(fo, "Unable to execute " + cmd + ". Shell execution", true);
		return;
	}
	FILE *fimg = fopen(img.c_str(), "rb");
	if (fimg == NULL) {
		html_perror(fo, "Unable to open " + img + " for reading", true);
		return;
	}
	int c;
	#ifdef WIN32
	setmode(fileno(result), O_BINARY);
	#endif
	while ((c = getc(fimg)) != EOF)
		putc(c, result);
	fclose(fimg);
	(void)unlink(dot.c_str());
	(void)unlink(img.c_str());
	(void)rmdir(dot_dir.c_str());
}
