#!/bin/sh
#
# Commit the obfuscated files overwriting the original ones
# Can be tailored to do other things
#
#
find . -name '*.obf' -print |
sed 's/^\(.*\).obf$/mv -f \1.obf \1\
chmod 444 \1/' |
sh
