#!/bin/sh
#
# Compare simple_cpp against cc
#
# $Id: cpp-test,v 1.2 2003/08/16 21:38:48 dds Exp $
#

gcc -ansi -E $1 | grep -v '^#' | grep -v '^[ 	]*$' >cc.out &&
i386/cscout.exe -E $1 >simple_cpp.out &&
diff --ignore-all-space --ignore-blank-lines --ignore-matching='^# [0-9]' simple_cpp.out cc.out
